### ISSUE TITLE
conflict between yuiCssOptimize and fixVendorPrefixes

### ISSUE THREAD

**Issue by allosushi** [mape/connect-assetmanager-handlers#5]
yuiCssOptimize removes unecessary semicolons in the css code but without the semicolon the regex for fixVendorPrefixes doesn't work.

example :

div.test {
-vendor-border-radius:3px;
}

after yuiCssOptimize (the semicolon is gone):

div.test {-vendor-border-radius:3px}

then fixVendorPrefixes has no effect

**Comment by mape** [comment]
Can't you just move yuiCssOptimize after fixVendorPrefixes?

**Comment by allosushi** [comment]
yes that's the solution
i've put the yuiCssOptimize in the postManipulate object
